
version: "1.2"

# path
#problem_path: /extrahome0/HF_datasets/s1k
#problem_path: "di-zhang-fdu/AIME_1983_2024" # GAIR/LIMO, simplescaling/s1K
#problem_path: "/extrahome0/user/output/evol_s1k/v1/evol_s1k_v.pkl" # GAIR/LIMO, simplescaling/s1K
#problem_path: "/extrahome0/user/data/math7500/math7500.pkl" # GAIR/LIMO, simplescaling/s1K
#problem_path: "/media/user/data/ga/math7500/math7500.pkl" # GAIR/LIMO, simplescaling/s1K
#problem_path: "/media/user/data/ga/math7500/hard_math5k.pkl"
# problem_path: /extrahome0/user/data/srl_math_benchmark/amc23/test.jsonl
problem_path: /inspire/hdd/global_user/USER_ID/user/zhang/data/srl_math_benchmark/
# data_name: amc23 # limo, s1k, o1j, aime
data_name: amc23 # aime24,amc23,math500
# data_type: "trained"
data_type: "base" # base
# output_path: "/extrahome0/user/output/"
output_path: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/wz/math_infer"
#output_path: "/media/user/output"
order: "-"
overwrite: False

# 外部vllm server配置信息
base_url: "http://localhost:8000/v1" # vLLM服务的地址 端口1/2 8000/8012
api_key: "EMPTY"  # 如果设置了API密钥需要填写
#model_path: "/extrahome0/pretrain/nlp/Qwen2.5-7B-Instruct"
# model_path: /extrahome0/user/output/s1k_evol_sft/qwen-it/20250317090045_qwen-it_lr7e-07_e1_bs16_ra0/checkpoint-40
model_path: "/inspire/hdd/global_user/USER_ID/user/models/Qwen2.5-7B-Instruct"
# model_path: '/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/wz/output_limo_new_v1/s1k_new_mutation_sft/qwen-it/20251225000855_qwen-it_lr1e-05_e1_bs64_ra0/checkpoint-4'
# model_path: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/wz/output_s1k_new_no_gt/s1k_new_mutation_sft/qwen-it/20251218103008_qwen-it_lr1e-05_e1_bs64_ra0/checkpoint-4"

# 初始进化种群配置
batch_size: 32
pop_size: 4
gen_responses_temp: 0.6
max_response_len: 2048
#gen_responses_prompt: "/root/workspace/code/reason/evol/gen_resp.txt"
gen_responses_prompt: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/gen_resp.txt"

# crossover
gen_critic_temp: 0.6
max_critic_len: 2048
#critic_prompt: "/root/workspace/code/reason/evol/critic.txt"
critic_prompt: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/critic.txt"

gen_author_temp: 0.6
max_author_len: 2048
#author_prompt: "/root/workspace/code/reason/evol/author.txt"
author_prompt: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/author.txt"

# mutation
gen_mutation_temp: 0.6
max_mutation_len: 2048
# mutation_prompt_1: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/mutation_v1.txt"
# mutation_prompt_2: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-v2/ifdr-main-qwen1.5/evol/mutation_v1.txt"
mutation_prompt_1: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/mutation_v2_no_gt.txt"
mutation_prompt_2: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/mutation_v1_no_gt.txt"
mutation_prompt_3: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/mutation_v3_no_gt.txt"

# 进化配置
iter_num: 3

critic_correct_fusion_pmt: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/critic_correct_fusion_pmt.txt"
critic_correct_guidance_pmt: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/critic_correct_guidance_pmt.txt"
critic_wrong_exploration_pmt: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/critic_wrong_exploration_pmt.txt"

judge_critique_pmt: "/inspire/hdd/global_user/USER_ID/user/code/ifdr-main-wz-v2/evol/judge_critique_pmt.txt"